### ISSUE TITLE
Publish plugin on npm

### ISSUE THREAD

**Issue by antonlvovych** [admhlt/retext-usage#1]
I'm just tried to install your plugin from npm and seems you didn't publish it. I think it should be here: https://www.npmjs.com/package/retext-usage

**Comment by adamhollett** [comment]
Hi GEEKIAM!

Sorry you weren't able to install the plugin. The reason it's not available on npm is because it's not finished yet. I've only managed to get through about half the patterns I want to include. I work on this sporadically in my spare time, so it might be a while before it's ready and available on npm.

**Comment by antonlvovych** [comment]
So you recommend do not use this plugin until you finish it because it doesn't work properly, yep?

If not and It works even with about half the patterns you want to include, you should think about publishing it. You will be able add new features later and just update package to the newest version on npm.

**Comment by nodatall** [comment]
I am also interested in using this, even in its current form.

**Comment by adamhollett** [comment]
Thank you both for the push. :) The package is now published at <https://www.npmjs.com/package/retext-usage>.
